GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/696e884120ddff404d60c61e


###

DELETE http://localhost:3001/api/persons/abubu

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jojo Jones",
    "number": "12239312"
}

###
GET http://localhost:3001/info